# Generated by Django 3.2.15 on 2022-10-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
